-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 12:37:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blogpessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogpessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogpessoal` DEFAULT CHARACTER SET utf8 ;
USE `blogpessoal` ;

-- -----------------------------------------------------
-- Table `blogpessoal`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogpessoal`.`tb_usuario` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogpessoal`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogpessoal`.`tb_tema` (
  `id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogpessoal`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogpessoal`.`tb_postagem` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  `data` DATE NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  `tb_tema_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagem_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_postagem_tb_tema1_idx` (`tb_tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `blogpessoal`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_tb_tema1`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `blogpessoal`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
